name:         reply
version:      0.1.0-dev
description:  Utilities for recording and replaying API interactions
homepage:     https://github.com/matanlurey/reply.dart
authors:
              - Matan Lurey <matanl@lurey.org>

environment:
  sdk: '>1.19.0 <2.0.0'

dev_dependencies:
  test:
