name:         reply
version:      0.1.3-dev
description:  Utilities for recording and replaying API interactions
homepage:     https://github.com/matanlurey/reply.dart
authors:
              - Matan Lurey <matanl@lurey.org>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  collection: '^1.1.0'

dev_dependencies:
  test: '^0.12.17'
