name:         reply
version:      0.1.2-dev
description:  Utilities for recording and replaying API interactions
homepage:     https://github.com/matanlurey/reply.dart
authors:
              - Matan Lurey <matanl@lurey.org>

environment:
  sdk: '>=1.20.0-dev <2.0.0'

dependencies:
  collection:

dev_dependencies:
  test:
